/**
 * @clapp/codegen — generated README emission (CLAPP-031).
 *
 * Every generated app ships a README that documents what the app serves
 * (routes, forms, navigation, storage, API mocks, acceptance journeys)
 * AND its honest limitations — including the storage-replay limitation
 * sentence VERBATIM, as required by the codegen worker packet:
 *
 *   minidom replay never gates on storage; P4's paired runner owns
 *   storage verification
 */

import type { ResolvedStorage } from './storage';
import type { SynthesisPlan } from './synthesis-contract';
import type { PageModule } from './gen-server';

export interface ReadmeEmissionInput {
  plan: SynthesisPlan;
  packageName: string;
  port: number;
  pageModules: PageModule[];
  redirects: Array<{ fromPath: string; toPath: string }>;
  storage: ResolvedStorage;
  apiNotes: string[];
  redirectNotes: string[];
  routeNotes: string[];
}

function triggerLabel(
  trigger:
    | { kind: 'link'; elementId: string }
    | { kind: 'form-submit'; formId: string }
    | { kind: 'redirect'; reason: string },
): string {
  switch (trigger.kind) {
    case 'link':
      return `link ${trigger.elementId}`;
    case 'form-submit':
      return `form-submit ${trigger.formId}`;
    case 'redirect':
      return `redirect (${trigger.reason})`;
  }
}

/** Renders the generated app's README.md (deterministic). */
export function renderReadme(input: ReadmeEmissionInput): string {
  const { plan, packageName, port, pageModules, redirects, storage, apiNotes, redirectNotes, routeNotes } = input;
  const routesByPageId = new Map(plan.routes.map((route) => [route.pageId, route]));
  const lines: string[] = [];

  lines.push(`# ${plan.application.name} — synthesized candidate app`);
  lines.push('');
  lines.push('This app was GENERATED by `@clapp/codegen` (CLAPP-031); do not edit it.');
  lines.push(`It renders the SynthesisPlan \`${plan.application.id}\` (contract v${plan.planVersion})`);
  lines.push(`derived from Behavioral-IR model \`${plan.application.sourceModelId}\`.`);
  lines.push('');
  lines.push('## Running');
  lines.push('');
  lines.push('The app has ZERO runtime dependencies (node stdlib only):');
  lines.push('');
  lines.push('```bash');
  lines.push(`bun ${plan.server.startCommand.startsWith('bun') ? plan.server.startCommand.slice('bun'.length).trim() : 'server.ts'}`);
  lines.push('```');
  lines.push('');
  lines.push(`- Listens on \`127.0.0.1\`, planned port \`${port}\`.`);
  lines.push('- The `PORT` environment variable overrides the port at runtime (`PORT=0` picks an ephemeral port).');
  lines.push(`- Health check: \`${plan.server.healthPath}\` answers 200 once the server is ready.`);
  lines.push('- On startup one JSON line `{ "url": ..., "port": ... }` is printed to stdout.');
  lines.push('- Unknown paths answer 404 with an HTML page (`data-testid="not-found"`).');
  lines.push('');
  lines.push('## Routes');
  lines.push('');
  if (pageModules.length === 0) {
    lines.push('(no planned routes)');
  } else {
    for (const module of pageModules) {
      const route = plan.routes.find((candidate) => candidate.path === module.routePath);
      const page = plan.pages.find((candidate) => candidate.id === route?.pageId);
      lines.push(`- \`${module.routePath}\` — ${page?.title ?? '(untitled page)'} (\`${module.modulePath}\`)`);
    }
  }
  for (const note of routeNotes) {
    lines.push(`- NOTE: ${note}`);
  }
  lines.push('');
  lines.push('## Forms');
  lines.push('');
  const forms = plan.pages.flatMap((page) => {
    const route = routesByPageId.get(page.id);
    return page.forms.map((form) => ({ page, route, form }));
  });
  if (forms.length === 0) {
    lines.push('(no planned forms)');
  } else {
    for (const { page, route, form } of forms) {
      lines.push(`### \`${form.id}\` on \`${route?.path ?? '?'}\` (${page.title})`);
      lines.push('');
      lines.push(`- Submits \`${form.method.toUpperCase()}\` to \`${form.action}\` (submit button: "${form.submitLabel}"${form.submitTestId !== undefined ? `, data-testid \`${form.submitTestId}\`` : ''}).`);
      for (const field of form.fields) {
        const bits = [`name \`${field.name}\``, `type \`${field.type}\``];
        if (field.required === true) {
          bits.push('required');
        }
        if (field.testId !== undefined) {
          bits.push(`data-testid \`${field.testId}\``);
        }
        lines.push(`  - ${field.label} — ${bits.join(', ')}`);
      }
      lines.push('');
    }
  }
  lines.push('## Navigation graph');
  lines.push('');
  if (plan.navigation.length === 0) {
    lines.push('(no planned transitions)');
  } else {
    const routePath = (routeId: string): string => plan.routes.find((route) => route.id === routeId)?.path ?? `(${routeId})`;
    for (const transition of plan.navigation) {
      lines.push(`- ${routePath(transition.fromRouteId)} → ${routePath(transition.toRouteId)} via ${triggerLabel(transition.trigger)}`);
    }
  }
  if (redirects.length > 0) {
    lines.push('');
    lines.push('Redirect transitions whose from-route carries no page are served as `308` redirects:');
    for (const redirect of redirects) {
      lines.push(`- \`${redirect.fromPath}\` → \`${redirect.toPath}\``);
    }
  }
  for (const note of redirectNotes) {
    lines.push(`- NOTE: ${note}`);
  }
  lines.push('');
  lines.push('## Storage bindings');
  lines.push('');
  if (plan.storage.length === 0) {
    lines.push('(no planned storage bindings)');
  } else {
    for (const binding of plan.storage) {
      const transitions = binding.writtenOn.map((id) => plan.navigation.find((t) => t.id === id)?.id ?? id);
      lines.push(`- \`${binding.key}\` (${binding.storage}) — written after ${transitions.map((id) => `\`${id}\``).join(', ')}`);
    }
    lines.push('');
    lines.push('Cookie bindings are emitted as `Set-Cookie` headers on the destination routes');
    lines.push('(value = the key name — a documented placeholder: the plan carries no captured');
    lines.push('values). localStorage/sessionStorage bindings are emitted as inline `<script>`');
    lines.push('writes embedded in the destination pages (same placeholder value semantics);');
    lines.push('real browsers execute them.');
    if (storage.serverBindingCount > 0) {
      lines.push('');
      lines.push(`${storage.serverBindingCount} 'server' storage ${storage.serverBindingCount === 1 ? 'binding is' : 'bindings are'} documented here only — the mock backend is stateless by design.`);
    }
    for (const note of storage.skipped) {
      lines.push(`- NOTE: ${note}`);
    }
  }
  lines.push('');
  lines.push('Honest limitation (verbatim): minidom replay never gates on storage; P4\'s paired runner owns storage verification.');
  lines.push('');
  lines.push('## API endpoints and mocks');
  lines.push('');
  if (plan.api.endpoints.length === 0) {
    lines.push('(no planned api endpoints)');
  } else {
    for (const endpoint of plan.api.endpoints) {
      const mocks = plan.api.mocks.filter((mock) => mock.endpointId === endpoint.id);
      lines.push(`- \`${endpoint.method} ${endpoint.urlPattern}\` (\`${endpoint.id}\`) — ${mocks.length} mock${mocks.length === 1 ? '' : 's'}`);
      for (const mock of mocks) {
        lines.push(`  - \`${mock.id}\`: ${mock.statusCode}${mock.bodyJson === undefined ? ' (empty body)' : ` \`${JSON.stringify(mock.bodyJson)}\``}`);
      }
    }
    lines.push('');
    lines.push('Matching rules: a `:name` pattern segment matches exactly one non-empty path');
    lines.push('segment; the FIRST mock by declaration order serves; endpoints without mocks');
    lines.push('answer `501` with a JSON body naming the endpoint id; a path matching a pattern');
    lines.push('with the wrong method answers `405`.');
    for (const note of apiNotes) {
      lines.push(`- NOTE: ${note}`);
    }
  }
  lines.push('');
  lines.push('## Acceptance journeys');
  lines.push('');
  if (plan.acceptance.length === 0) {
    lines.push('(no planned acceptance journeys)');
  } else {
    for (const acceptance of plan.acceptance) {
      lines.push(`- \`${acceptance.journeyId}\` — ${acceptance.purpose}`);
      lines.push(`  - Expected end route: \`${acceptance.expectedRoute}\` · must-see elements: ${acceptance.mustSeeElementIds.length}`);
      for (const step of acceptance.steps) {
        lines.push(`  - ${step}`);
      }
    }
    lines.push('');
    lines.push('The full Journey records live with the journey store (@clapp/journey); the');
    lines.push('generated test suite (CLAPP-032, @clapp/gentests) replays each journey against');
    lines.push('this app and enforces the expectations above.');
  }
  lines.push('');
  lines.push('## Assumptions');
  lines.push('');
  if (plan.assumptions.length === 0) {
    lines.push('(none declared)');
  } else {
    for (const assumption of plan.assumptions) {
      lines.push(`- ${assumption}`);
    }
  }
  lines.push('');
  lines.push('## Constraints');
  lines.push('');
  if (plan.constraints.length === 0) {
    lines.push('(none declared)');
  } else {
    for (const constraint of plan.constraints) {
      lines.push(`- ${constraint}`);
    }
  }
  lines.push('');
  lines.push('## Known limitations (honest)');
  lines.push('');
  lines.push('- Pages are static pre-rendered HTML: no client-side scripting beyond the declared');
  lines.push('  storage writes, no dynamic data, and request bodies are never read.');
  lines.push('- The plan element list is flat: document order and landmark structure are preserved,');
  lines.push('  but exact parent/child nesting of the observed app is not reproduced.');
  lines.push('- Planned images carry alt text but no sources; deterministic placeholder SVGs are');
  lines.push('  served instead (the alt text is embedded, so the placeholders stay accessible).');
  lines.push('- Checkbox fields render unchecked (the plan contract carries no field state).');
  lines.push('- `server` storage bindings and api request/response schemas are documented, not');
  lines.push('  enforced (the mock backend is stateless and serves canned bodies verbatim).');
  lines.push('- Package name: `' + packageName + '` (slugified application name with the');
  lines.push('  `clapp-app-` prefix; start command: `' + plan.server.startCommand + '`).');
  lines.push('');
  return lines.join('\n');
}
