/**
 * @clapp/codegen — generated server source emission (CLAPP-031).
 *
 * Emits the complete, self-contained `server.ts` of a generated candidate
 * app: a zero-dependency node:http server (runs under bun or any runtime
 * with node http + TS support; the generated start command uses bun) that
 * serves the pre-rendered page modules, the mock backend, synthesized
 * image assets, redirect transitions, cookie storage bindings, the health
 * path, and a 404 page.
 *
 * Request precedence (documented in the generated header):
 *   1. planned pages (exact path; GET/HEAD + POST for form submissions)
 *   2. mock backend API patterns (":name" matches one non-empty segment;
 *      wrong method → 405; no mocks → 501 naming the endpoint id)
 *   3. redirect transitions (from-routes without pages → 308 + Location)
 *   4. synthesized image assets (exact /assets/<name>.svg)
 *   5. health path (200 "ok" when not itself a page)
 *   6. 404 HTML page (data-testid="not-found", b01 convention)
 *
 * Once listening, the server prints one JSON line { url, port } to stdout
 * (how test harnesses learn an ephemeral PORT=0 port), then serves until
 * SIGINT/SIGTERM. Request bodies are drained and never read (pages are
 * static; the mock backend ignores payloads).
 */

import type { ApiRouteEntry } from './mock-backend';
import type { SynthesisPlan } from './synthesis-contract';

export interface PageModule {
  /** Import path relative to the app root, e.g. "pages/index.html.ts". */
  modulePath: string;
  /** Import identifier, e.g. "routeIndex". */
  identifier: string;
  /** The served route path. */
  routePath: string;
}

export interface ServerEmissionInput {
  plan: SynthesisPlan;
  port: number;
  healthPath: string;
  homePath: string;
  pageModules: PageModule[];
  apiEntries: ApiRouteEntry[];
  redirects: Array<{ fromPath: string; toPath: string }>;
  cookieRoutes: Map<string, string[]>;
  assets: Map<string, string>;
}

function recordLiteral(
  entries: Array<[string, string]>,
  typeAnnotation: string,
  emptyComment: string,
): string {
  if (entries.length === 0) {
    return `const ${typeAnnotation} = {}; // ${emptyComment}`;
  }
  const lines = entries.map(([key, value]) => `  ${JSON.stringify(key)}: ${value},`);
  return [`const ${typeAnnotation} = {`, ...lines, '};'].join('\n');
}

function apiEntryLiteral(entry: ApiRouteEntry): string {
  const lines = ['  {', `    endpointId: ${JSON.stringify(entry.endpointId)},`, `    method: ${JSON.stringify(entry.method)},`, `    segments: ${JSON.stringify(entry.segments)},`, '    mocks: ['];
  for (const mock of entry.mocks) {
    const body = mock.bodyJson === undefined ? '' : `, bodyJson: ${JSON.stringify(mock.bodyJson)}`;
    lines.push(`      { statusCode: ${mock.statusCode}${body} },`);
  }
  lines.push('    ],', '  },');
  return lines.join('\n');
}

function notFoundPageLiteral(homePath: string): string {
  // Emitted as a joined array so the generated source stays quote-simple.
  const lines = [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head><meta charset="utf-8"><title>404 — page not found</title></head>',
    '<body>',
    '<main>',
    '<h1>Page not found</h1>',
    '<p data-testid="not-found">This synthesized app has no page at this address.</p>',
    `<p><a href="${homePath}">Back to home</a></p>`,
    '</main>',
    '</body>',
    '</html>',
  ];
  return `[${lines.map((line) => JSON.stringify(line)).join(', ')}, ''].join('\\n')`;
}

/** Renders the complete generated server.ts source. */
export function renderServerSource(input: ServerEmissionInput): string {
  const { plan, port, healthPath, homePath, pageModules, apiEntries, redirects, cookieRoutes, assets } = input;

  const imports = [...pageModules]
    .sort((a, b) => (a.modulePath < b.modulePath ? -1 : a.modulePath > b.modulePath ? 1 : 0))
    .map((module) => `import { html as ${module.identifier} } from './${module.modulePath}';`);

  const routeEntries: Array<[string, string]> = pageModules.map((module) => [module.routePath, module.identifier]);
  const apiBlock =
    apiEntries.length === 0
      ? 'const apiRoutes: ApiRouteEntry[] = []; // no planned api endpoints'
      : ['const apiRoutes: ApiRouteEntry[] = [', ...apiEntries.map(apiEntryLiteral), '];'].join('\n');
  const redirectEntries: Array<[string, string]> = redirects.map((redirect) => [
    redirect.fromPath,
    JSON.stringify(redirect.toPath),
  ]);
  const cookieEntries: Array<[string, string]> = [...cookieRoutes.entries()].map(([path, values]) => [
    path,
    JSON.stringify(values),
  ]);
  const assetEntries: Array<[string, string]> = [...assets.entries()].map(([name, svg]) => [
    name,
    JSON.stringify(svg),
  ]);

  return `// Generated by @clapp/codegen (CLAPP-031) — synthesized candidate app server. DO NOT EDIT.
// Application: ${plan.application.name} (${plan.application.id}) · plan version ${plan.planVersion}.
// Regenerate from the SynthesisPlan instead of editing this file.
//
// Zero runtime dependencies (node stdlib only). Start: ${plan.server.startCommand}
// from this package root. Planned port ${port}; the PORT env var overrides it
// (PORT=0 → ephemeral). One JSON line { url, port } is printed once listening.
// Health path: ${healthPath} · Pages: ${pageModules.length} · API endpoints: ${apiEntries.length}.
// Request bodies are drained, never read: pages are static pre-rendered HTML.
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
${imports.join('\n')}

interface MockEntry {
  statusCode: number;
  bodyJson?: unknown;
}

interface ApiRouteEntry {
  endpointId: string;
  method: string;
  segments: string[];
  mocks: MockEntry[];
}

const HOST = '127.0.0.1';
const DEFAULT_PORT = ${port};
const HEALTH_PATH = ${JSON.stringify(healthPath)};
const HOME_PATH = ${JSON.stringify(homePath)};

/** Planned pages: route path → pre-rendered HTML (byte-deterministic). */
${recordLiteral(routeEntries, 'routes: Record<string, string>', 'no planned pages')}

/** Planned API endpoints (mock backend; first mock by declaration order serves). */
${apiBlock}

/** Redirect transitions whose from-route carries no page: path → target path. */
${recordLiteral(redirectEntries, 'redirects: Record<string, string>', 'no redirect transitions without pages')}

/** Cookie storage bindings: route path → Set-Cookie values (placeholder values: value = key). */
${recordLiteral(cookieEntries, 'cookieRoutes: Record<string, string[]>', 'no cookie storage bindings')}

/** Synthesized placeholder SVG assets for planned images. */
${recordLiteral(assetEntries, 'assets: Record<string, string>', 'no planned images')}

const NOT_FOUND_PAGE: string = ${notFoundPageLiteral(homePath)};

function pathSegments(path: string): string[] {
  // Strict split: only the LEADING empty segment is dropped — a trailing
  // slash is NOT normalized away (page routes match paths exactly).
  const parts = path.split('/');
  return parts.length > 0 && parts[0] === '' ? parts.slice(1) : parts;
}

function segmentsMatchRoute(route: ApiRouteEntry, segments: string[]): boolean {
  if (route.segments.length !== segments.length) {
    return false;
  }
  for (let index = 0; index < route.segments.length; index += 1) {
    const pattern = route.segments[index];
    const actual = segments[index];
    if (pattern === undefined || actual === undefined || actual === '') {
      return false;
    }
    if (pattern.startsWith(':')) {
      continue;
    }
    if (pattern !== actual) {
      return false;
    }
  }
  return true;
}

/** All endpoints whose pattern matches the path, in declaration order. */
function matchApiRoutes(path: string): ApiRouteEntry[] {
  const segments = pathSegments(path);
  const matches: ApiRouteEntry[] = [];
  for (const route of apiRoutes) {
    if (segmentsMatchRoute(route, segments)) {
      matches.push(route);
    }
  }
  return matches;
}

function requestPath(request: IncomingMessage): string {
  const raw = (request.url ?? '/').split('?')[0]?.split('#')[0] ?? '/';
  try {
    return decodeURIComponent(raw);
  } catch {
    return raw;
  }
}

function send(
  response: ServerResponse,
  statusCode: number,
  contentType: string,
  body: string,
  headOnly: boolean,
  cookies?: string[],
): void {
  const headers: Record<string, string | string[]> = {
    'content-type': contentType,
    'content-length': String(Buffer.byteLength(body, 'utf8')),
    'cache-control': 'no-store',
  };
  if (cookies !== undefined && cookies.length > 0) {
    headers['set-cookie'] = cookies;
  }
  response.writeHead(statusCode, headers);
  response.end(headOnly ? undefined : body);
}

function handle(request: IncomingMessage, response: ServerResponse): void {
  request.resume(); // drain any request body (never read)
  const method = (request.method ?? 'GET').toUpperCase();
  const headOnly = method === 'HEAD';
  const path = requestPath(request);

  // 1. Planned pages (GET/HEAD + POST for same-origin form submissions).
  const page = routes[path];
  if (page !== undefined) {
    if (method === 'GET' || method === 'HEAD' || method === 'POST') {
      send(response, 200, 'text/html; charset=utf-8', page, headOnly, cookieRoutes[path]);
      return;
    }
    send(response, 405, 'text/plain; charset=utf-8', 'method not allowed\\n', false);
    return;
  }

  // 2. Mock backend: the first endpoint matching path AND method serves;
  //    path matches without a method match answer 405 naming the first
  //    path-matching endpoint (deterministic) and listing the allowed methods.
  const apiMatches = matchApiRoutes(path);
  if (apiMatches.length > 0) {
    const apiRoute = apiMatches.find((route) => route.method.toUpperCase() === method);
    if (apiRoute === undefined) {
      const first = apiMatches[0];
      if (first === undefined) {
        send(response, 404, 'text/html; charset=utf-8', NOT_FOUND_PAGE, headOnly);
        return;
      }
      send(
        response,
        405,
        'application/json; charset=utf-8',
        JSON.stringify({ error: 'method not allowed', endpointId: first.endpointId, allowed: apiMatches.map((route) => route.method) }),
        headOnly,
      );
      return;
    }
    const mock = apiRoute.mocks[0];
    if (mock === undefined) {
      send(
        response,
        501,
        'application/json; charset=utf-8',
        JSON.stringify({ error: 'no mock response declared for endpoint', endpointId: apiRoute.endpointId }),
        headOnly,
      );
      return;
    }
    const body = mock.bodyJson === undefined ? '' : JSON.stringify(mock.bodyJson, null, 2);
    send(response, mock.statusCode, 'application/json; charset=utf-8', body, headOnly);
    return;
  }

  // 3. Redirect transitions (from-routes without pages) — 308 preserves methods.
  const redirectTarget = redirects[path];
  if (redirectTarget !== undefined) {
    if (method === 'GET' || method === 'HEAD' || method === 'POST') {
      response.writeHead(308, { location: redirectTarget, 'cache-control': 'no-store' });
      response.end(headOnly ? undefined : '');
      return;
    }
    send(response, 405, 'text/plain; charset=utf-8', 'method not allowed\\n', false);
    return;
  }

  // 4. Synthesized image assets.
  if (path.startsWith('/assets/')) {
    const asset = assets[path.slice('/assets/'.length)];
    if (asset !== undefined) {
      send(response, 200, 'image/svg+xml', asset, headOnly);
      return;
    }
  }

  // 5. Health path (when not itself a planned page).
  if (path === HEALTH_PATH) {
    if (method === 'GET' || method === 'HEAD') {
      send(response, 200, 'text/plain; charset=utf-8', 'ok\\n', headOnly);
      return;
    }
    send(response, 405, 'text/plain; charset=utf-8', 'method not allowed\\n', false);
    return;
  }

  // 6. Unknown path.
  send(response, 404, 'text/html; charset=utf-8', NOT_FOUND_PAGE, headOnly);
}

const server = createServer((request, response) => {
  handle(request, response);
});

server.on('error', (error) => {
  process.stderr.write('server error: ' + String(error) + '\\n');
  process.exit(1);
});

const portArg = Number(process.env.PORT ?? DEFAULT_PORT);
const port = Number.isInteger(portArg) && portArg >= 0 && portArg <= 65535 ? portArg : DEFAULT_PORT;
server.listen(port, HOST, () => {
  const address = server.address();
  const actual = typeof address === 'object' && address !== null ? address.port : port;
  process.stdout.write(JSON.stringify({ url: 'http://' + HOST + ':' + actual + '/', port: actual }) + '\\n');
});

function shutdown(): void {
  server.close(() => {
    process.exit(0);
  });
}

process.on('SIGINT', shutdown);
process.on('SIGTERM', shutdown);
`;
}
