/**
 * @clapp/codegen — generateApp: SynthesisPlan → runnable candidate app (CLAPP-031).
 *
 * Renders a plan (synthesis-contract v0.1 mirror) into a complete file tree:
 *
 *   package.json          — zero-dependency app package (type: module, scripts.start)
 *   server.ts             — zero-dep node:http server (pages + mocks + storage)
 *   pages/<slug>.html.ts  — one pre-rendered HTML module per planned route
 *   README.md             — generated documentation incl. honest limitations
 *
 * DETERMINISM: the same plan (plus options) always produces a byte-identical
 * file tree — no timestamps, no randomness, sorted file list. Structural
 * validation of a plan is @clapp/plan's job (canonical owner); codegen
 * performs only the minimal defensive checks below and THROWS on them:
 *
 * - planVersion must equal PLAN_VERSION;
 * - duplicate route paths; a page whose routeId names no planned route;
 * - two pages claiming the same route; invalid heading levels; an element
 *   whose formId names no form declared on its own page;
 * - a non-integer/out-of-range port (planned or option).
 *
 * Lenient + documented (surfaced as notes in the generated README, never
 * silently dropped): a route whose pageId names no page (serves no page —
 * a redirect transition from it then serves 308), mocks naming undeclared
 * endpoints, storage bindings with unresolvable writtenOn transitions,
 * redirect transitions whose from-route carries a rendered page (the page
 * wins), 'server' storage bindings (documented only).
 */

import { renderServerSource, type PageModule } from './gen-server';
import { renderReadme } from './gen-readme';
import { renderPageHtml } from './render-page';
import { buildApiTable, apiEndpointLabel } from './mock-backend';
import { resolveStorage } from './storage';
import { PLAN_VERSION, type SynthesisPlan } from './synthesis-contract';
import { CODEGEN_PACKAGE_PREFIX, type AppManifest, type GeneratedApp, type GeneratedFile, type GenerateOptions } from './types';
import { imageAssetName, imageAssetSvg, pageModuleIdentifier, pageModulePath, slugify } from './util';

function assertPort(port: number, label: string): number {
  if (!Number.isInteger(port) || port < 0 || port > 65535) {
    throw new TypeError(`codegen: ${label} must be an integer between 0 and 65535, got ${String(port)}`);
  }
  return port;
}

/** Escapes HTML for embedding in a generated TS template literal. */
function forTemplateLiteral(html: string): string {
  return html.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

/** Renders a page module: a header comment + `export const html = ...`. */
function renderPageModule(routePath: string, pageId: string, title: string, html: string): string {
  return [
    `// Generated by @clapp/codegen (CLAPP-031) — page module for route ${routePath}. DO NOT EDIT.`,
    `// PlannedPage ${pageId} (${title}) — pre-rendered, byte-deterministic HTML.`,
    `export const html = \`${forTemplateLiteral(html)}\`;`,
    '',
  ].join('\n');
}

/** Allocates a unique page-module path + identifier per route path. */
function allocateModule(routePath: string, used: Set<string>): { modulePath: string; identifier: string } {
  const base = pageModulePath(routePath);
  if (!used.has(base)) {
    used.add(base);
    return { modulePath: base, identifier: pageModuleIdentifier(base) };
  }
  for (let attempt = 2; attempt < 1000; attempt += 1) {
    const candidate = base.replace(/\.html\.ts$/, `-${attempt}.html.ts`);
    if (!used.has(candidate)) {
      used.add(candidate);
      return { modulePath: candidate, identifier: pageModuleIdentifier(candidate) };
    }
  }
  throw new TypeError(`codegen: cannot allocate a unique page module path for ${routePath}`);
}

/**
 * Generates the complete candidate app for a plan. See the module doc for
 * the defensive checks (throws) and the lenient cases (README notes).
 */
export function generateApp(plan: SynthesisPlan, options: GenerateOptions = {}): GeneratedApp {
  if (plan.planVersion !== PLAN_VERSION) {
    throw new TypeError(`codegen: plan.planVersion ${JSON.stringify(plan.planVersion)} does not equal PLAN_VERSION ${JSON.stringify(PLAN_VERSION)}`);
  }
  const port = assertPort(options.port ?? plan.server.port, options.port !== undefined ? 'GenerateOptions.port' : 'plan.server.port');

  // ---- lookups + defensive checks ------------------------------------------
  const routesById = new Map(plan.routes.map((route) => [route.id, route]));
  const pagesByRouteId = new Map<string, string>(); // routeId → page id (first claim wins; duplicates throw)
  for (const page of plan.pages) {
    if (!routesById.has(page.routeId)) {
      throw new TypeError(`codegen: page ${page.id} references routeId ${page.routeId} which is not declared in plan.routes`);
    }
    const claimedBy = pagesByRouteId.get(page.routeId);
    if (claimedBy !== undefined) {
      throw new TypeError(`codegen: route ${page.routeId} is claimed by both page ${claimedBy} and page ${page.id}`);
    }
    pagesByRouteId.set(page.routeId, page.id);
  }
  const routePaths = new Set<string>();
  for (const route of plan.routes) {
    if (routePaths.has(route.path)) {
      throw new TypeError(`codegen: duplicate route path ${route.path}`);
    }
    routePaths.add(route.path);
  }

  const routeNotes: string[] = [];
  const pagesById = new Map(plan.pages.map((page) => [page.id, page]));
  const pageModules: PageModule[] = [];
  const usedModulePaths = new Set<string>();
  const assets = new Map<string, string>();

  // ---- pages (render + collect synthesized image assets) --------------------
  const renderedHtml = new Map<string, string>(); // page id → html
  const storage = resolveStorage(plan);
  for (const page of plan.pages) {
    const scripts = storage.pageScripts.get(page.id) ?? [];
    const html = renderPageHtml(page, scripts);
    renderedHtml.set(page.id, html);
    for (const element of page.elements) {
      if (element.kind === 'image') {
        const alt = element.alt ?? element.name ?? '';
        assets.set(imageAssetName(element.alt ?? element.name ?? element.id), imageAssetSvg(alt));
      }
    }
  }
  for (const route of plan.routes) {
    const page = route.pageId !== undefined ? pagesById.get(route.pageId) : undefined;
    if (page === undefined) {
      routeNotes.push(`route ${route.id} (${route.path}) names pageId ${route.pageId} which is not declared in plan.pages — the route serves no page (404 unless a redirect transition applies)`);
      continue;
    }
    const { modulePath, identifier } = allocateModule(route.path, usedModulePaths);
    pageModules.push({ modulePath, identifier, routePath: route.path });
  }

  // ---- mock backend ----------------------------------------------------------
  const api = buildApiTable(plan);

  // ---- redirects (from-routes without a rendered page) -----------------------
  const redirects: Array<{ fromPath: string; toPath: string }> = [];
  const redirectNotes: string[] = [];
  for (const transition of plan.navigation) {
    if (transition.trigger.kind !== 'redirect') {
      continue;
    }
    const fromRoute = routesById.get(transition.fromRouteId);
    const toRoute = routesById.get(transition.toRouteId);
    if (fromRoute === undefined || toRoute === undefined) {
      redirectNotes.push(`redirect transition ${transition.id} references a route missing from plan.routes (${fromRoute === undefined ? transition.fromRouteId : transition.toRouteId}) — not served`);
      continue;
    }
    if (pagesByRouteId.has(fromRoute.id)) {
      redirectNotes.push(`redirect transition ${transition.id}: from-route ${fromRoute.path} carries a rendered page — the page wins, no redirect is served`);
      continue;
    }
    if (!redirects.some((candidate) => candidate.fromPath === fromRoute.path)) {
      redirects.push({ fromPath: fromRoute.path, toPath: toRoute.path });
    }
  }

  // ---- emitted files -----------------------------------------------------------
  const effectiveHomePath = plan.application.entrypoints[0] ?? plan.routes[0]?.path ?? '/';
  const serverSource = renderServerSource({
    plan,
    port,
    healthPath: plan.server.healthPath,
    homePath: effectiveHomePath,
    pageModules,
    apiEntries: api.entries,
    redirects,
    cookieRoutes: storage.cookieRoutes,
    assets,
  });

  const appNameSlug = slugify(plan.application.name);
  const packageName = `${CODEGEN_PACKAGE_PREFIX}${appNameSlug === '' ? 'app' : appNameSlug}`;
  const packageJson = `${JSON.stringify(
    {
      name: packageName,
      version: '0.1.0',
      private: true,
      type: 'module',
      description: `Synthesized candidate app for ${plan.application.name} — generated by @clapp/codegen from SynthesisPlan ${plan.application.id} (contract v${plan.planVersion}).`,
      scripts: { start: plan.server.startCommand },
    },
    null,
    2,
  )}\n`;

  const readme = renderReadme({
    plan,
    packageName,
    port,
    pageModules,
    redirects,
    storage,
    apiNotes: api.notes,
    redirectNotes,
    routeNotes,
  });

  const files: GeneratedFile[] = [
    { path: 'package.json', contents: packageJson },
    { path: 'server.ts', contents: serverSource },
    ...pageModules.map((module) => {
      const route = plan.routes.find((candidate) => candidate.path === module.routePath);
      const page = route === undefined ? undefined : pagesById.get(route.pageId);
      const html = page === undefined ? '' : renderedHtml.get(page.id) ?? '';
      return {
        path: module.modulePath,
        contents: renderPageModule(module.routePath, page?.id ?? '?', page?.title ?? '(untitled)', html),
      };
    }),
    { path: 'README.md', contents: readme },
  ].sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));

  const manifest: AppManifest = {
    packageName,
    startCommand: plan.server.startCommand,
    port,
    healthPath: plan.server.healthPath,
    routePaths: plan.routes.map((route) => route.path),
    apiEndpoints: plan.api.endpoints.map(apiEndpointLabel),
  };

  return { files, manifest };
}
